language: python

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - sudo apt-get install -y libimage-exiftool-perl

install:
  - pip install -r requirements-dev.txt
  - pip install .

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

script:
  - pytest

notifications:
  email: false
