language: python
dist: xenial

before_install:
  - sudo apt-get install -y libimage-exiftool-perl

install:
  - pip install tox

matrix:
  include:
    - stage: Lint and Code Style
      python: 3.8
      env: TOXENV=linters

    - stage: Tests
      python: 3.8
      env: TOXENV=py38

    - python: 3.7
      env: TOXENV=py37

    - python: 3.6
      env: TOXENV=py36

  allow_failures:
    # For now, allow the linters to fail
    - env: TOXENV=linters

script:
  - tox

notifications:
  email: false
