language: python
dist: xenial

before_install:
  - sudo apt-get install -y libimage-exiftool-perl

install:
  - pip install tox

matrix:
  include:
    - stage: Tests (Python 3.6)
      python: 3.6
      env: TOXENV=py36

script:
  - tox

notifications:
  email: false
